### 1. What is a Python library? Why do we use Python libraries?


Ans. Python Library is a collection of functions and methods that can be used repeatedly in different programs.
It makes python programming simple and convenient for the programmer as we do not need to write same code again and again.

### 2. What is the difference between Numpy array and List?

Ans. Numpy array is a collection of homogenous data 
     Numpy list is a data structure that can store hetrogenous data 

In [1]:
##3.  Find the shape, size and dimension of the following array?

import numpy as np
a= np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])

shape = a.shape 
size = a.size   
dimensions = a.ndim

print("Shape of the array:", shape)
print("Size of the array:", size)
print("Number of dimensions of the array:", dimensions)

Shape of the array: (3, 4)
Size of the array: 12
Number of dimensions of the array: 2


In [2]:
##4. Write python code to access the first row of the following array?

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

first_row = a[0]

print("First row of the array:", first_row)


First row of the array: [1 2 3 4]


In [3]:
#5. How do you access the element at the third row and fourth column from the given numpy array?

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

element = a[2, 3]

print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


In [4]:
#6. Write code to extract all odd-indexed elements from the given numpy array?

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

flattened_a = a.flatten()

odd_indexed_elements = flattened_a[1::2]

print("Odd-indexed elements from the array:")
print(odd_indexed_elements)

Odd-indexed elements from the array:
[ 2  4  6  8 10 12]


In [5]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.72249599 0.94911539 0.53812218]
 [0.42295593 0.61221172 0.91645599]
 [0.07731303 0.23046747 0.90851944]]


#8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand: generates random values from a uniform distribution over the interval (0, 1)
np.random.randn: Generates random values from a standard normal distribution (mean=0, standard deviation=1).

In [6]:
# 9. Write code to increase the dimension of the following array?

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

new_arr = np.expand_dims(arr, axis=0)

print("Original array shape:", arr.shape)
print("New array shape:", new_arr.shape)

Original array shape: (3, 4)
New array shape: (1, 3, 4)


In [7]:
#10. How to transpose the following array in NumPy?

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Transpose the array using .T attribute
transposed_arr = arr.T

print("Original array:",arr)
print("\nTransposed array:",transposed_arr)


Original array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [8]:
import numpy as np

A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# 1. Index-wise multiplication
index_wise_multiplication = A2 * B2

# 2. Matrix multiplication
matrix_multiplication = np.dot(A2, B2.T)  # Using B2.T for matrix multiplication

# 3. Add both matrices
addition = A2 + B2

# 4. Subtract matrix B from A
subtraction = A2 - B2

# 5. Divide Matrix B by A
division = B2 / A2

# Print the results
print("1. Index-wise multiplication:\n", index_wise_multiplication)
print("\n2. Matrix multiplication:\n", matrix_multiplication)
print("\n3. Addition:\n", addition)
print("\n4. Subtraction:\n", subtraction)
print("\n5. Division:\n", division)

1. Index-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12.  Which function in Numpy can be used to swap the byte order of an array?

function np.ndarray.byteswap() can be used to swap the byte order of an array in NumPy. 


### 13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function is used to compute the multiplicative inverse of a matrix. 
It's significant in linear algebra as it allows you to find the inverse of a square matrix, which is essential for solving systems of linear equations and other mathematical operations.

### 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. 
It returns a new array with the specified shape. You can use it to reshape arrays into different dimensions.

### 15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. When arrays with different shapes are involved in arithmetic operations, NumPy automatically broadcasts the smaller array to match the shape of the larger array, without making explicit copies of the data. This enables you to write vectorized code that operates on arrays of different shapes efficiently.